### ISSUE TITLE
1.1_BasicLandingPage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#1]
## Value Proposition

*As a* user,

*I need* to be able to see the landing page and

*to be able to* see 6 different tattoo ideas

----------

## Description

The Landing Page shows a random collection of tattoo-ideas. The buttons and the burgemenu will *not* be implemented
[
<img width="272" alt="Bildschirmfoto 2022-12-10 um 11 08 34" src="https://user-images.githubusercontent.com/115539625/206851249-885bc586-8cdf-4141-be9c-5ce7ae5ab33e.png">
](url)

---------------------

## Acceptance Criteria

- [x] Header is visible
- [x] Main shows 6 different tattoos (hardcoded)
- [x] Footer is visible

-----------------

## Tasks

- [x] create new next.js project
- [x] add repo in github
- [x] write header, main, footer components
- [x] style components
~~header has a burgermenu (no functional)~~
~~main has filter buttons (not functional) and 6 picturecards~~
