### ISSUE TITLE
2.1_SetupDB

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#12]
## Value Proposition

As a developer, I need to set up a database to store the artist-objects.
As a user, I want to access the data via frontend, just like before. 
​

## Description

Right now, the data ist stored in the project package itself. But it should be fetched from an API that communicates with the database.
​
## Acceptance Criteria

- [x] all artists object are stored in a database (MongoDB)
- [x] an API endpoint handles the communication between frontend and database
- [x] when using the app, all data is served from the API
      ​

## Tasks

- [x] setup MongoDB: Create new collection, Transfer the artist-objects from project to database
- [x] setup driver: Install Mongoose, create Artist-Schema, configure communication (dbConnect)
- [x] write an API that handles request and response - for now only GET-method
- [x] write a useFetch-hook. Implement the hook in all components, that use the artist-data
~~update filter-and array methods with CRUD-operators~~
      ​
