### ISSUE TITLE
2.2_CloudinaryFetch

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#13]
## Value Proposition

As a developer, I want to store the image-data in a cloudinary media-library.
As a user, I want to access the data via the app.
​

## Description

Again, a backend task. The tattoo-imgs should be transferred from the project to a cloud. The frontend is not touched.
​

## Acceptance Criteria

- [x] imgs are saved at a cloudinary media-library
- [x] the img-urls inside the artist-objects point to the public ID of the respectively img-file in the media-library
- [x] the imgs are shown just like before, but under the hood fetched from the cloud.
      ​

## Tasks

- [x] setup cloudinary: create folder and preset 
- [x] install npm-package next-cloudinary
- [x] setup local environment for next-cloudinary
- [x] implement CldImage-component in my Picture-component, so all the tattoo-pics are directly fetched from cloudinary
      ​
