### ISSUE TITLE
2.3_CreateNewArtist

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#14]
## Value Proposition

As a user, I want to be able to create my own artist profile with the following information: Artistname, location and 4 pictures. 
I need a form, tu upload this information.
​

## Description

This is a form task. The user-information should be stored in the database, while the img-files are transferred to the cloud. After the submit, the app should now show said information at the other pages (i.e. random-page, artist-page etc.)
​I will NOT style the form in this US.

## Acceptance Criteria

- [x] new form-page (/newUser) with 6 input elements: Artistname, location and 4 picture-files-> All Inputs are required
- [x] after the submit, the data is stored at MongoDB, the files are uploaded to cloudinary.
- [x] the new information can be accessed via the app 

      
## Tasks

- [x] create new page: /newUser 
- [x] create form with with 2 text and 4 file inputs and a submit button
- [x] update API-endpoint to accept POST
- [x] write a async submit-hook: 
- [x] the file upload must be first: Use cloudinary REST-API for the upload
- [x] From the cloudinary response extract the publicIDs of the pictures and store them as URLs inside the new artist object (img-array).
- [x] Implement the hook in the form.
      ​

**Comment by ufelgen** [comment]
Hey Alex, finde deine User Stories für das Backend gut portioniert und beschrieben! Hier würde ich noch spezifizieren, ob denn 4 Bilder hochgeladen werden MÜSSEN, oder ob z.B. auch eins reicht und man evtl später (neue US) mehr Bilder hinzufügen kann. Und vielleicht spezifizierst du noch, wofür die 2 Textinputfelder sind: Vor- und Nachname? gab es nicht mal eine Künstlername-Option?

**Comment by onebarloop** [comment]
> Hey Alex, finde deine User Stories für das Backend gut portioniert und beschrieben! Hier würde ich noch spezifizieren, ob denn 4 Bilder hochgeladen werden MÜSSEN, oder ob z.B. auch eins reicht und man evtl später (neue US) mehr Bilder hinzufügen kann. Und vielleicht spezifizierst du noch, wofür die 2 Textinputfelder sind: Vor- und Nachname? gab es nicht mal eine Künstlername-Option?

Yes, guter Punkt. Mach ich direkt - danke fürs Drüberschauen :)
