### ISSUE TITLE
1.2_ArtistPage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#2]
## Value Proposition

*As a*  user, i want to be be able to visit the artists page. I should be able to return to the homepage via the home button

----------

## Description

When a tattoo Idea is clicked, the user should be forwarded to the artists page

![AP](https://user-images.githubusercontent.com/115539625/207146777-ae7a2c1e-ad65-404b-b389-7f7c8470c0f2.png)

---------------------

## Acceptance Criteria

- [x] tattoo Ideas are Links to the artist page
- [x] artist page shows artist details
- [x] footer has a working home button

-----------------

## Tasks

- [x] write helper function to remove blank spaces with replaceAll()-method
- [x] create Artists Array, with artist objects like so: 

> `const Artists = [{name: "string", location: "string", slug: "namestringwithoutspaces", tattoos: ["url1", "url2", "url3"]}]`

- [x] create template for artist page -> dynamic link via artist name
- [x] page should render artist name, location and all tattoos of the artist
- [x] create button in the footer that leads to  /pages/index.tsx

**Comment by altanguellue** [comment]
1. Bei Value Proposition würde es sich anbieten das Template 1:1 zu übernehmen:

_As a ...(user, Author, logged in User...)

I need ...(describe the goal)

to be able to ...(describe the reason)_


2. Finde den Aufbau der Tasks sehr übersichtlich und gut!
