### ISSUE TITLE
3.1_Map

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#23]
## Value Proposition

As a user, I want to see a map with all  tattoo artists
​

## Description

Implementation of a map feature. The map is its own page, with a marker for each tattoo-studio/artist. The marker should be clickable and forward to the artist page
​

## Acceptance Criteria

- [ ] see all studios/artists on a map
- [ ] when creating a new artist, a marker should be added to the map
- [ ] when clicked, a popup with a link to the specific artist page should appear above the marker
      ​

## Tasks

- [ ] install packages: leaflet, leaflet react, leaflet types 
- [ ] create new component "Map", with custom icon
- [ ] create new page "map" and dynamically import Map without ssr
- [ ] write function to reverse geocode from geoapify
- [ ] implement function in artist-creation, so the adress is transformed in geocode
- [ ] inside "Map", map over all artists, and show a marker on the specific geolocation
      ​
