### ISSUE TITLE
3.2_PreviewUploadImages

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#24]
## Value Proposition

As a user, I want to check the images, before I upload them on the "New User" Page. 
​

## Description

Right now, the images can only be selected via file select, without any preview. After the update, the user should be able to select up to 4 pictures and see them in a little preview.
​

## Acceptance Criteria

- [x] at the New User page, there is a button to add new pictures. ​Every added picture should be visible as a preview
- [x] the preview pictures can be also deleted with a little x-button

## Tasks

- [x] rewrite the newuser-page to have a controlled input field 
- [x] all added files should be stored in a state-array
- [x] for each entry in this array, one Image-component should be rendered as preview -> number of pictures should be capped at 4. 
- [x] write a button components, that removes the selected picture from the array, and thus from the preview
- [x] rewrite the uploadUserData function to work with the edited form-page -> the files now don't come from the form but from the state-array
- [x] type everything correctly

**Comment by NeeleWaehnke** [comment]
Sehr gut und klar formuliert was du vorhast mit der US!

**Comment by onebarloop** [comment]
> Sehr gut und klar formuliert was du vorhast mit der US!

Danke Neele! Ich hoffe es hat geklappt!
