### ISSUE TITLE
3.3_CalendarImplementation

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#26]
## Value Proposition

As a user, I want to be able to check the artists time schedule. 
As an artist, I want to be able to publish my time schedule.

## Description

The task is, to implement a calendar solution (react-calender): While creating an artists, a popup should show a calendar, where the artists can log in his*her time schedule. On the artist page, this timeschedule should be visible for the user
​

## Acceptance Criteria

- [x] Popup un page /newuser allows the user to enter specific dates with exact time
- [x] On submit, this data is stored along with all the other userdata
- [x] on the /[slug] (i.e. Artist)-page, the timeschedule will be visible for the user
      ​

## Tasks

- [x] install react-datepicker
- [x] restructure artist-object, so it can hold calendar data
- [x] implement calendar as a popup at /newuser-page
- [x] on submit, save committed dates in artist-object
- [x] use this data to render a timeschedule on each individual artist-page
      ​
