### ISSUE TITLE
3.4_LocalStorage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#28]
## Value Proposition

As a user, I want my favorites list saved between sessions. After visiting an artistpage, I want to be able to go back to the page I came from via the home button.
​

## Description

This is a quick one: Local storage should keep track of the state-hook for favorites and viewpoint. 

## Acceptance Criteria

- [x] both states (viewpoint and likes) are saved in local storage
- [x] home button from the artist page forwards to the pageview, the user came from
      ​
## Tasks

- [x] install react-use-local-storage-state
- [x] write custom hooks for local storage functions and state
- [x] use hooks for viewpoint and likes

      ​
