### ISSUE TITLE
1.3_FilterMainpage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#3]
## Value Proposition

As a user I want to be able to see a list of Artists on the landingpage.

I need to be able to switch between regular view and artist view

----------

## Description

![Image](https://user-images.githubusercontent.com/115539625/207144673-28dafb82-bd83-4949-acfa-4096b1049445.png)

---------------------

## Acceptance Criteria

- [x] Mainpage renders all Artist Objects with information (name and location) and one tattoo
- [x] Buttons to switch between regular view (random tattoos) and artist view works

-----------------

## Tasks

- [x] Change artist-objects, so they have a prop "id". nanoid is used for random id generation. This will later be handled by MongoDB
- [x] write a component to render a list of all artists.
- [x] style this component
- [x] implement on mainpage with conditional rendering - mainview : artistview. Store the values in state object.
- [x] write two button components to switch between views: "Surprise me" (for mainview) and "Artists"
- [x] style the button components

**Comment by AntjeWalter** [comment]
Ich glaube, ich verstehe deine Buttons/Filter nicht. Man ist als erstes auf einer random Tattoo-Sammlung und kann dann oben auf "Artists" klicken. Aber wo ist in deiner description der Button für die random Seite? Ich hätte das jetzt an der Stelle bei Filter oder so erwartet. Vielleicht kannst du das noch etwas präzisieren :) Ansonsten siehts cool aus!

**Comment by onebarloop** [comment]
Danke für den Kommentar, hab die Änderungen eingefügt
