### ISSUE TITLE
4.1_LikeButtonArtistPage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#30]
## Value Proposition

As a user, I want to be able to add artists to my favorite list, when I am visiting an artist page.

## Description

Simple task: Add a "like" button to the artist-page. Right now, the like-buttons only appear in the list views (browse artists and favorites)
​

## Acceptance Criteria

- [x] Like button on the artists (/[slug]) page
- [x] Button adds artist to the likes local storage array
      ​

## Tasks

- [x] import useLike-hook at artist page
- [x] Implement button on artist-page, pass hook to event listener
      ​
