### ISSUE TITLE
4.2_MapUserLocation

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#31]
## Value Proposition

As a user, I want to see my own position on the map with a visually different marker than the artists.

## Description

Right now, the user position on the map is not shown. This should be changed, so the user is represented with a marker on the map.
​

## Acceptance Criteria

- [x] Map shows user position with a special marker
      ​

## Tasks

- [x] call [Navigator.geoloaction](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation) when visiting /map
- [x] get geolocation from the Geolocation object
- [x] pass Geolocation to the map component
- [x] Render a specific marker at this position
      ​
