### ISSUE TITLE
4.3_EnlargePictures

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#32]
## Value Proposition

As a user, I want to be able to see the full picture of a tattoo when clicking on it.
​

## Description

When visiting the artist-page, the user can see 4 tattoo-pictures. This US makes them clickable, so they enlarge over the whole screen.
​

## Acceptance Criteria

- [x] Pictures on artist-page (/[slug]) are clickable
- [x] when clicked, they fill the whole screen
- [x] pictures can be closed via a X-button
      ​

## Tasks

- [x] write new Component (PicturePopUp). This component renders the picture over the whole screen
- [x] mount this component via conditional rendering, when a picture is clicked. Track with state-hook
- [x] Give the component the picture-url as prop
- [x] implement a button component inside the PopUp, that clears the state and unmounts the PopUp-component
      ​
