### ISSUE TITLE
4.4_FindArtistOnMap

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#35]
## Value Proposition

As a user, I want to be able to select the different artists via a dropdown menu on the map. I also want to be redirected to the map, directly from the artist-page
​

## Description

A dropdown menu selects the different artists on the map. The selected artist becomes highlighted. A button redeirects from the artist-page to the map-page, highlighting the artist.
​

## Acceptance Criteria

- [x] dropdown menu selects artist
- [x] icon changes when selected
- [x] button leads from artist-page to map-page, selecting the artist
      ​

## Tasks

- [x] install `react-select`
- [x] make component, then implement on map page
- [x] create new icons for selection
- [x] implement button on artist-page
      ​
