### ISSUE TITLE
1.4_LikeButton

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#4]
## Value Proposition

As a user, I want to be able to bookmark (like) specific artists.

----------

## Description

![HP-Artists](https://user-images.githubusercontent.com/115539625/207146393-9560ddec-dd86-4d6b-8276-8c0f8a39d756.png)

---------------------

## Acceptance Criteria

- [x] Like button toggles status and changes color
- [x] bookmark filter-button works and main only renders bookmarked artists

-----------------

## Tasks

- [x] create new state: array of the id's of the bookmarked cards
- [x] add button component to artist card. button should add or remove the id from the state-array 
- [x] add condition in styled components to switch between button-colors 
- [x] create filter button - reuse artist-button component
- [x] add option "bookmarked" to the view State 
- [x] implement conditional rendering of bookmarked items on mainpage. Reuse component for rendering all artists

**Comment by AntjeWalter** [comment]
Ich glaube, das war bei deinen vorherigen US auch so; deine Value Proposition ist unvollständig. Ich weiß nicht, wie wichtig das ist, dass das die drei Zeilen sind, vielleicht müsstest du das nochmal einen Coach fragen :) Der Rest der US sieht für mich gut aus!
