### ISSUE TITLE
1.5_RandomizeTattoos

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#5]
## Value Proposition

As a user, I want to be greeted by a random collection of 6 different tattoos, every time I visit the homepage. I want to be able to create a new random selection via a button click.
​

## Description

No changes in style, just a randomizer for all img files

![Image](https://user-images.githubusercontent.com/115539625/207145647-bae8e32d-4ed5-429c-91f5-3e19c7f819db.png)

## Acceptance Criteria

- [x] New random tatoos on every page refresh
- [x] New random tatoos with click on the surprise me button
      ​

## Tasks

- [x] write a randomizer function that takes in all items (urls) of all img-array of all the artist-objects and gives back an array of six urls
- [x] call randomizer function on component mount
- [x] call randomizer function on button click
- [x] map over the array and produce and img-tag for each of the items with src=item-value
      ​

**Comment by AntjeWalter** [comment]
Baut auf meinem Kommentar von einer früheren US auf; ich denke es fehlt ein Button, um auf die random Tattoo-Seite zurück zu kommen. Vielleicht kannst du an dieser Stelle dann auch schon eine Navbar mit einfügen

**Comment by onebarloop** [comment]
Auf eine Navbar will ich zu diesem Zeitpunkt noch verzichten, darum kümmere ich mich später. Aber den Button habe ich eingebaut!
