### ISSUE TITLE
0.2_NavigationMenu

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/capstone-project#6]
## Value Proposition

As a user, I want to be able to navigate the App via a Menu in the header
​

## Description
Refactor Navigation buttons in Main into a burgermenu in the Header
![Bildschirmfoto 2023-01-04 um 09 13 53](https://user-images.githubusercontent.com/115539625/210511758-4fdf4285-cfed-4be0-9d1f-3dfae598ae93.png)

## Acceptance Criteria

- [ ] Burgermenu expands when clicked on the button in header
- [ ] links in the expanded burgermenu are functional
      ​

## Tasks

- [ ] write navigation component
- [ ] style component
- [ ] refactor all buttons and Links into navigation component. Right now this are 6 buttons: Random View/Artist View/ Favorite View and Homepage / New User Page / Map Page
